# Generated by Django 2.2.8 on 2020-02-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200229_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
