# Generated by Django 2.2.8 on 2020-03-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='uploadDate',
            field=models.DateTimeField(auto_created=True, verbose_name='date and time of upload'),
        ),
    ]
