# Generated by Django 2.2.8 on 2020-03-02 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200302_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='uploadDate',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='date and time of upload'),
        ),
        migrations.AlterField(
            model_name='assessmentimage',
            name='image',
            field=models.ImageField(upload_to='elements/', verbose_name='Image'),
        ),
    ]
