# Generated by Django 2.2.8 on 2020-03-03 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200302_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentimage',
            name='assessment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assessmentPic', to='core.Assessment'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content of the question'),
        ),
    ]
