# Generated by Django 2.2.8 on 2020-03-13 21:13

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200303_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessmentDate',
            field=models.DateField(blank=True, null=True, validators=[core.validators.validate_AssessmentDate], verbose_name='day of assessment'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='courseCode',
            field=models.CharField(max_length=10, validators=[core.validators.validate_CourseCode], verbose_name='assessment course code'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assessmentPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=10)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_votes', to='core.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'answer', 'vote_type')},
            },
        ),
    ]
