# Generated by Django 2.2.8 on 2020-03-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200320_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ManyToManyField(related_name='questionAnswer', to='core.Question'),
        ),
    ]
