# Generated by Django 2.2.8 on 2020-03-20 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20200320_0426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVotes',
            new_name='UserVote',
        ),
    ]
