# Generated by Django 2.2.8 on 2020-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200324_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='courseTitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='course title of assessments'),
        ),
    ]
