# Generated by Django 2.2.8 on 2020-04-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200407_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='AnswerImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='answer image'),
        ),
    ]
