# Generated by Django 2.2.8 on 2020-05-29 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200508_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
