# Generated by Django 2.2.8 on 2020-06-26 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20200530_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myFavorite', to='core.Assessment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myList', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
