# Generated by Django 2.2.8 on 2020-04-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountprofile', '0004_auto_20200409_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profile/', verbose_name='user avatar'),
        ),
    ]
