# Generated by Django 2.2.8 on 2020-05-08 09:42

import accountprofile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountprofile', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='studentId',
            field=models.IntegerField(validators=[accountprofile.validators.validate_id], verbose_name='student id'),
        ),
    ]
